### ISSUE TITLE
Initial build of project created with this archetype failed due to wrong NOTICE file

### ISSUE THREAD

**Issue by arpost** [akalsan/eurekaclinical-service-archetype#4]
I tried to create a project called eurekaclinical-notification-service, and `mvn clean install` resulted in the following build failure:

```
[ERROR] Existing NOTICE file '/private/tmp/eurekaclinical-notification-service/NOTICE' doesn't match expected NOTICE file: /private/tmp/eurekaclinical-notification-service/target/NOTICE.expected
27c27
<   eurekaclinical-notification-service under Apache License, Version 2.0

---
>   eurekaclinical-service-template under Apache License, Version 2.0
```

Can you template the project name in NOTICE?

**Comment by akalsan** [comment]
Not including the NOTICE file and having mvn notice:generate seem to be the standard way to do it. Also, the new project might have extra dependencies that might need to go into the NOTICE file.
if you think the same i will remove the NOTICE file and check in.
